import {
  SiReact,
  SiTypescript,
  SiNodedotjs,
  SiNextdotjs,
  SiSpringboot,
  SiDocker,
  SiHtml5,
  SiJavascript,
  SiVite,
  SiTailwindcss,
  SiPostgresql,
  SiMysql,
  SiMongodb,
  SiVercel,
  SiRailway,
  SiHostinger,
  SiJira,
  SiInsomnia,
  SiPostman,
  SiGithubactions,
  SiJest,
  SiZod,
  SiExpress,
  SiPython,
  SiIntellijidea,
  SiGooglecloud,
  SiAngular,
  SiSqlite,
  SiBootstrap,
  SiSupabase,
  SiNestjs,
  SiCursor,
  SiClaude,
  SiGithubcopilot,
  SiGooglegemini,
  SiThreedotjs,
  SiGsap,
  SiWebgl,
  SiFramer,
  SiRedux,
  SiReactquery,
  SiShadcnui,
  SiStorybook,
  SiFigma,
  SiGraphql,
  SiPrisma,
  SiDrizzle,
  SiTrpc,
  SiSocketdotio,
  SiStripe,
  SiFirebase,
  SiKubernetes,
  SiTerraform,
  SiCloudflare,
  SiNetlify,
  SiVitest,
  SiCypress,
  SiTestinglibrary,
  SiEslint,
  SiPrettier,
  SiTurborepo,
  SiBun,
  SiI18Next,
} from "react-icons/si";
import {
  FaJava,
  FaLinux,
  FaGitAlt,
  FaGithub,
  FaAws,
  FaSass,
  FaCss3Alt,
} from "react-icons/fa6";
import { TbApi } from "react-icons/tb";
import { VscLayers, VscAzure, VscVscode, VscOpenai } from "react-icons/vsc";
import { DiRedis, DiJenkins, DiNginx } from "react-icons/di";
import { GrDocker } from "react-icons/gr";
import { Icon } from "./icons";
import { Zustand } from "../../public/svg/zustand";

export const stackIcons: Record<string, Icon> = {
  // Front:
  "CSS": { icon: FaCss3Alt, bg: `#1572B666` },
  "HTML": { icon: SiHtml5, bg: `#E34F2666` },
  "JavaScript": { icon: SiJavascript, bg: `#F7DF1E66` },
  "TypeScript": { icon: SiTypescript, bg: `#3178C666` },
  "React": { icon: SiReact, bg: `#61DAFB66` },
  "Next.js": { icon: SiNextdotjs, bg: `#ffffff66` },
  "Vite": { icon: SiVite, bg: `#9135FF66` },
  "Tailwind CSS": { icon: SiTailwindcss, bg: `#06B6D466` },
  "Angular": { icon: SiAngular, bg: `#DD003166` },
  "Sass": { icon: FaSass, bg: `#CC669966` },
  "Bootstrap": { icon: SiBootstrap, bg: `#7952B366` },
  "Redux": { icon: SiRedux, bg: `#764ABC66` },
  "React Query": { icon: SiReactquery, bg: `#FF415466` },
  "shadcn/ui": { icon: SiShadcnui, bg: `#ffffff66` },
  "Storybook": { icon: SiStorybook, bg: `#FF478566` },
  "Figma": { icon: SiFigma, bg: `#F24E1E66` },
  "i18next": { icon: SiI18Next, bg: `#26A69A66` },

  // 3D / Motion (o que move este portfólio):
  "Three.js": { icon: SiThreedotjs, bg: `#ffffff66` },
  // Não existe marca do R3F no Simple Icons; ele é Three.js em React.
  "React Three Fiber": { icon: SiThreedotjs, bg: `#ffffff66` },
  "WebGL": { icon: SiWebgl, bg: `#99000066` },
  "GLSL": { icon: SiWebgl, bg: `#5586A466` },
  "GSAP": { icon: SiGsap, bg: `#0AE44866` },
  "Framer Motion": { icon: SiFramer, bg: `#0055FF66` },

  // Back:
  Java: { icon: FaJava, bg: `#ED8B0066` },
  "Spring Boot": { icon: SiSpringboot, bg: `#6DB33F66` },
  "Node.js": { icon: SiNodedotjs, bg: `#33993366` },
  "Nestjs": { icon: SiNestjs, bg: `#E0234E66` },
  "API RESTful": { icon: TbApi, bg: `#00968866` },
  "Arquitetura MVC": { icon: VscLayers, bg: `#8B5CF666` },
  "Zod": { icon: SiZod, bg: `#3E67B166` },
  "Express.js": { icon: SiExpress, bg: `#0A0A0A66` },
  "Python": { icon: SiPython, bg: `#3776AB66` },
  "Redis": { icon: DiRedis, bg: `#DC382D66` },
  "Zustand": { icon: Zustand, bg: `#7952B366` },
  "GraphQL": { icon: SiGraphql, bg: `#E1009866` },
  "Prisma": { icon: SiPrisma, bg: `#2D374866` },
  "Drizzle": { icon: SiDrizzle, bg: `#C5F74F66` },
  "tRPC": { icon: SiTrpc, bg: `#2596BE66` },
  "Socket.io": { icon: SiSocketdotio, bg: `#ffffff66` },
  "Stripe": { icon: SiStripe, bg: `#635BFF66` },
  "Bun": { icon: SiBun, bg: `#FBF0DF66` },

  // DevOps:
  "Docker": { icon: SiDocker, bg: `#2496ED66` },
  "Docker Compose": { icon: GrDocker, bg: `#2496ED66` },
  "GitHub Actions": { icon: SiGithubactions, bg: `#2088FF66` },
  "Kubernetes": { icon: SiKubernetes, bg: `#326CE566` },
  "Terraform": { icon: SiTerraform, bg: `#844FBA66` },
  "Turborepo": { icon: SiTurborepo, bg: `#EF444466` },

  // Cloud:
  "Azure": { icon: VscAzure, bg: `#0089D666` },
  "Vercel": { icon: SiVercel, bg: `#0A0A0A66` },
  "Railway": { icon: SiRailway, bg: `#0B0D0E66` },
  "VPS Hostinger": { icon: SiHostinger, bg: `#673DE666` },
  "AWS": { icon: FaAws, bg: `#FF990066` },
  "GCP": { icon: SiGooglecloud, bg: `#4285F466` },
  "Nginx": { icon: DiNginx, bg: `#00963966` },
  "Cloudflare": { icon: SiCloudflare, bg: `#F3802066` },
  "Netlify": { icon: SiNetlify, bg: `#00C7B766` },
  "Firebase": { icon: SiFirebase, bg: `#DD2C0066` },

  // Tests:
  "Jest": { icon: SiJest, bg: `#C2132566` },
  "Jenkins": { icon: DiJenkins, bg: `#D2493966` },
  "Vitest": { icon: SiVitest, bg: `#6E9F1866` },
  "Cypress": { icon: SiCypress, bg: `#69D3A766` },
  "Testing Library": { icon: SiTestinglibrary, bg: `#E3333266` },

  // DB:
  "PostgreSQL": { icon: SiPostgresql, bg: `#4169E166` },
  "MySQL": { icon: SiMysql, bg: `#4479A166` },
  "MongoDB": { icon: SiMongodb, bg: `#47A24866` },
  "SQLite": { icon: SiSqlite, bg: `#003B5766` },
  "Supabase": { icon: SiSupabase, bg: `#3FCF8E66` },

  // Tools
  "Linux": { icon: FaLinux, bg: `#FCC62466` },
  "Git": { icon: FaGitAlt, bg: `#F03C2E66` },
  "GitHub": { icon: FaGithub, bg: `#18171766` },
  "Jira": { icon: SiJira, bg: `#0052CC66` },
  "Insomnia": { icon: SiInsomnia, bg: `#4000BF66` },
  "Postman": { icon: SiPostman, bg: `#FF6C3766` },
  "VS Code": { icon: VscVscode, bg: `#2F80ED66` },
  "IntelliJ IDEA": { icon: SiIntellijidea, bg: `#00000066` },
  "Cursor": { icon: SiCursor, bg: `#00000066` },
  "ESLint": { icon: SiEslint, bg: `#4B32C366` },
  "Prettier": { icon: SiPrettier, bg: `#F7B93E66` },

  // AI
  "Claude": { icon: SiClaude, bg: `#D9775766` },
  "Copilot": { icon: SiGithubcopilot, bg: `#ffffff66` },
  "Gemini": { icon: SiGooglegemini, bg: `#8E75B266` },
  "Codex": { icon: VscOpenai, bg: `#10A37F66` },
};
