import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { BlackHoleLight } from "@/components/BlackHoleLight";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col bg-[#F7F8FA] text-neutral-900 dark:bg-[#0B0E14] dark:text-white">
        <BlackHoleLight/>
        <div className="min-h-screen flex flex-col lg:flex-row">
          <main className="flex-1 z-10 relative">{children}</main>
        </div>
      </body>
    </html>
  );
}
